In [1]:
# coding = utf-8

In [23]:
import numpy as np
from torch import Tensor

In [3]:
datas = np.load('tang.npz')

In [4]:
type(datas)

numpy.lib.npyio.NpzFile

In [5]:
data = datas['data']

In [6]:
data[:2]

array([[8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8291, 6731,
        4770, 1787, 8118, 7577, 7066, 4817,  648, 7121, 1542, 6483, 7435,
        7686, 2889, 1671, 5862, 1949, 7066, 2596, 4785, 3629, 1379, 2703,
        7435, 6064, 6041, 4666, 4038, 4881, 7066, 4747, 1534,   70, 3788,
        3823, 7435, 4907, 5567,  201, 2834, 1519, 7066,  782,  782, 2063,
        2031,  846, 7435, 8290],
       [8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
        8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
     

In [7]:
datas.keys()

['ix2word', 'word2ix', 'data']

In [8]:
word2ix = datas['word2ix']

In [9]:
type(word2ix)  # 他把整个word2ix map 作为一个对象压入ndarray，不能用[0]用['key']也不行

numpy.ndarray

In [10]:
word2ix = word2ix.item()  # 这样才可以

In [11]:
word2ix['<START>']

8291

In [24]:
Tensor([word2ix['<START>']]).view(1, 1).long()

tensor([[ 8291]])

In [12]:
ix2word = datas['ix2word'].item()

In [13]:
ix2word[0]

'憁'

下面来看一首诗

In [14]:
data = datas['data']

In [15]:
data[0]

array([8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
       8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
       8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
       8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
       8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
       8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292,
       8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8292, 8291, 6731,
       4770, 1787, 8118, 7577, 7066, 4817,  648, 7121, 1542, 6483, 7435,
       7686, 2889, 1671, 5862, 1949, 7066, 2596, 4785, 3629, 1379, 2703,
       7435, 6064, 6041, 4666, 4038, 4881, 7066, 4747, 1534,   70, 3788,
       3823, 7435, 4907, 5567,  201, 2834, 1519, 7066,  782,  782, 2063,
       2031,  846, 7435, 8290], dtype=int32)

In [16]:
poetry_ix = data[123]

In [17]:
poetry = [ix2word[i] for i in poetry_ix]

In [18]:
poetry = ''.join(poetry)

In [19]:
poetry

'</s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s></s><START>少年一相见，飞辔河洛间。欢游不知罢，中路忽言还。泠泠鹍絃哀，悄悄冬夜闲。丈夫虽耿介，远別多苦颜。君行拜高堂，速驾难久攀。鸡鸣俦侣发，朔雪满河关。须臾在今夕，罇酌且循环。<EOP>'

查看size，一共有57,580首诗，每首诗最大长度是125；一共8293个字符。

In [20]:
data.shape

(57580, 125)

In [21]:
len(ix2word)

8293

In [22]:
len(word2ix)

8293